services:
  update_api:
    build: ./api
    ports:
      - "8080:8000"
    environment:
      - AWS_REGION=sa-east-1
      - S3_BUCKET=erp-auto-update
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
